### ISSUE TITLE
Excessive matcing on misplaced

### ISSUE THREAD

**Issue by bert8128** [eti-iniER/wordle-clone#1]
Say the answer is LUCID, and you guess DADDY.  Currently all of the Ds are rendered yellow, when only the first one should be.
If the answer was UDDER and you guess DADDY then the 1st D should be yellow and the 3rd green but the 2nd should be black.
If the answer is CRACK and you guess ACCESS then both Cs should be yellow.

**Comment by eti-iniER** [comment]
Noted. I'll work on that straight away... Was kinda struggling with implementing that the first time around.
Thanks for your feedback!
